trigger-deploy:
  needs:
    - job: build-web
      optional: false

  variables:
    UPSTREAM_CI_PROJECT_NAME: "${CI_PROJECT_NAME}"
    UPSTREAM_CORE_WEB_IMAGE: "${CI_REGISTRY_IMAGE}/${WEB_NAME_IMAGE}:${CI_COMMIT_TAG}"
    UPSTREAM_CORE_WORKER_IMAGE: "${CI_REGISTRY_IMAGE}/${WORKER_NAME_IMAGE}:${CI_COMMIT_TAG}"
    UPSTREAM_CORE_WEB_GITLAB_ENV_FILE: "${CORE_WEB_GITLAB_ENV_FILE}"
    UPSTREAM_CORE_WORKER_GITLAB_ENV_FILE: "${CORE_WORKER_GITLAB_ENV_FILE}"
    UPSTREAM_CORE_WEB_ENV_PATH: "${ENV_DIR}/${CORE_WEB_NAME_ENV_FILE}"
    UPSTREAM_CORE_WORKER_ENV_PATH: "${ENV_DIR}/${CORE_WORKER_NAME_ENV_FILE}"

  stage: trigger-deploy
  trigger:
    project: siracusa/iac
    branch: main
    strategy: mirror

  rules:
    - if: '$CI_COMMIT_TAG'
